global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']
  - job_name: 'proxmox-node'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.2:9100']
  - job_name: 'proxmox'
    metrics_path: /pve
    static_configs:
      - targets: ['192.168.50.2:9221']