---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres_name }}-{{ .Values.release }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: postgres-service
  replicas: {{ .Values.postgres_replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres_name }}-{{ .Values.release }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres_name }}-{{ .Values.release }}
    spec:
      containers:
        - name: {{ .Values.postgres_name }}-{{ .Values.release }}
          image: {{ .Values.postgres_image}}:{{ .Values.postgres_image_tag }}
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: news
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data/
      volumes:
        - name: postgres-volume

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service-{{ .Values.release }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.postgres_name }}-{{ .Values.release }}
  ports:
    - port: {{ .Values.postgres_port }}
      targetPort: {{ .Values.postgres_port }}
      protocol: TCP