---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      containers:
      - image: emiltk/kubernetes-config_backend:latest
        name: backend
        ports:
        - containerPort: 9000
      - image: emiltk/kubernetes-config_frontend:latest
        name: frontend
        ports:
        - containerPort: 80
