{
 "title": "Netology",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Disk Free",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node\"}[5m]))*100)"
    }
   ]
  },
  {
   "title": "CPU Load 1m",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(node_load1{job=\"node\"}) / count(count(node_cpu_seconds_total) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU Load 5m",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(node_load5{job=\"node\"}) / count(count(node_cpu_seconds_total) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU Load 15m",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(node_load15{job=\"node\"}) / count(count(node_cpu_seconds_total) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"node\"}",
     "legendFormat": "Memory Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\"}",
     "legendFormat": "memory Total"
    }
   ]
  }
 ]
}