---
grafana_version: 8.4.5

grafana_datasources:
  - name: prometheus
    type: prometheus
    url: "http://{{ hostvars['prometheus']['ansible_facts']['default_ipv4']['address'] }}:9090"
    basicAuth: false

grafana_security: { 
  admin_user: admin, 
  admin_password: NetologyMNT11
}
