---
prometheus_version: 2.34.0

prometheus_targets:
  node:
  - targets:
    - localhost:9100
    labels:
      env: netology
      job: node
  - targets:      
    - localhost:3000
    labels:
      env: netology
      job: grafana