---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-icmp-to-app1
  namespace: netology-np-demo
spec:
  podSelector:
    matchLabels:
      role: app2
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          role: app1
