---
- name: Install Pode_exporter
  hosts: node_exporter
  roles:
    - cloudalchemy.node_exporter
  tags: node_exporter

- name: Install Prometheus
  hosts: prometheus
  roles:
    - cloudalchemy.prometheus
  tags: prometheus

- name: Install Grafana
  hosts: grafana
  roles:
    - cloudalchemy.grafana
  tags: grafana