---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 51.250.4.93
    jenkins-agent-01:
      ansible_host: 84.252.128.212
    el-instance:
      ansible_host: "{{ lookup('env', 'EL_HOST') }}"
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: centos
