apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: emiltk/kubernetes-config_backend:latest
          name: backend
          volumeMounts:
            - mountPath: "/data"
              name: prod-volume
      volumes:
        - name: prod-volume
          persistentVolumeClaim:
            claimName: prod-pvc